activation: linear
batch_size: 64
control_channel_name: Analog In. | Ch.1 AIn-1 - Dem (AOut-3)
d_model: 64
data_dir: '/home/bugsie/PycharmProjects/FiberPhotometryAnalyzer/datafiles'
dim_feedforward: 1024
dropout: 0.1
fiber_channel_name: Analog In. | Ch.1 AIn-1 - Dem (AOut-2)
input_features: 1
latent_dim: 32
learning_rate: 0.00001
sparsity_lr: 0.1
lr_factor: 0.1
lr_patience: 30
max_epochs: 10000
max_time: 00:20:00:00
model: transformer_v4
monitor: val_loss
nhead: 4
normalization: quantile
scaling: 1.0
use_positional_encoding: false
num_layers: 3
num_workers: 9
precision: '16-mixed'
scheduler_frequency: 1
scheduler_interval: epoch
use_fiber: true
use_tracking: false
window_dim: 1024