program: sweep.py
name: sweep_config_1
method: bayes
metric:
  name: val_loss
  goal: minimize
parameters:
  activation:
    value: linear
  batch_size:
    value: 32
  data_dir:
    value: '/workspace/FiberPhotometryAnalyzer/datafiles'
  control_channel_name:
    value: Analog In. | Ch.1 AIn-1 - Dem (AOut-3)
  fiber_channel_name:
    value: Analog In. | Ch.1 AIn-1 - Dem (AOut-2)
  d_model:
    values:
        - 4
        - 8
        - 16
        - 64
  dim_feedforward:
    value: 2048
  dropout:
    value: 0.1
  input_features:
    value: 1
  latent_dim:
    value:
        - 4
  learning_rate:
    value: 0.001
  lr_factor:
    value: 0.1
  lr_patience:
    value: 5
  max_epochs:
    value: 100
  max_time:
    value: 00:02:00:00
  model:
    value: transformer_v2
  monitor:
    value: val_loss
  nhead:
    values:
        - 4
        - 8
        - 16
  normalization:
    value:
    - quantile
  num_layers:
    values:
      - 2
      - 4
      - 6
      - 12
  num_workers:
    value: 9
  use_positional_encoding:
    value:
      - false
  scaling:
    value:
      - 1.0
  precision:
    value: '16-mixed'
  scheduler_frequency:
    value: 1
  scheduler_interval:
    value: epoch
  use_fiber:
    value: true
  use_tracking:
    value: false
  window_dim:
    value: 1024
  sparsity_target:
    values:
      - 0.01
      - 0.05
      - 0.1
      - 0.2
  sparsity_weight:
    values:
      - 0.0000001
      - 0.000001
      - 0.00001
      - 0.0001
      - 0.001
      - 0.01
      - 0.1
      - 1.0